import type {
  DiaryEntry,
  Meeting,
  Patient,
  PatientGrowthPoint,
  PortalNotification,
  PsychologistProfile,
  SessionTypeSlice,
  WeeklySessions,
} from "./types";

// Fixed literal "today" so the portal's mock data stays deterministic instead
// of drifting relative to the real clock. Matches the "Wednesday" framing in
// the dashboard header and the July-2024 era already used by the admin
// portal's mock bookings/users.
export const TODAY = "2024-07-10";

export const PATIENTS: Patient[] = [
  {
    id: "p-1",
    name: "Alex Morgan",
    initials: "AM",
    status: "Active",
    primaryConcern: "Anxiety & stress management",
    lastSession: "2024-07-03",
    nextSession: "2024-07-10",
    totalSessions: 12,
    email: "alex@email.com",
    phone: "+1 555-0101",
    tags: ["Anxiety", "CBT"],
  },
  {
    id: "p-2",
    name: "Priya Shah",
    initials: "PS",
    status: "Active",
    primaryConcern: "Workplace burnout",
    lastSession: "2024-06-28",
    nextSession: "2024-07-10",
    totalSessions: 6,
    email: "priya@email.com",
    phone: "+1 555-0103",
    tags: ["Burnout", "Assessment"],
  },
  {
    id: "p-3",
    name: "Daniel Reyes",
    initials: "DR",
    status: "Active",
    primaryConcern: "Executive stress coaching",
    lastSession: "2024-06-20",
    nextSession: "2024-07-10",
    totalSessions: 9,
    email: "daniel@email.com",
    phone: "+1 555-0105",
    tags: ["Leadership", "Coaching"],
  },
  {
    id: "p-4",
    name: "Meera Iyer",
    initials: "MI",
    status: "New",
    primaryConcern: "Generalized anxiety (intake)",
    lastSession: null,
    nextSession: "2024-07-10",
    totalSessions: 0,
    email: "meera@email.com",
    phone: "+1 555-0109",
    tags: ["Intake"],
  },
  {
    id: "p-5",
    name: "Fatima Al-Hassan",
    initials: "FA",
    status: "Active",
    primaryConcern: "Grief & loss",
    lastSession: "2024-07-08",
    nextSession: "2024-07-17",
    totalSessions: 8,
    email: "fatima@email.com",
    phone: "+1 555-0106",
    tags: ["Grief", "Individual"],
  },
  {
    id: "p-6",
    name: "James Okafor",
    initials: "JO",
    status: "Active",
    primaryConcern: "Trauma & PTSD",
    lastSession: "2024-07-08",
    nextSession: null,
    totalSessions: 15,
    email: "james@email.com",
    phone: "+1 555-0110",
    tags: ["Trauma", "EMDR"],
  },
  {
    id: "p-7",
    name: "Emily Clarke",
    initials: "EC",
    status: "New",
    primaryConcern: "Social anxiety",
    lastSession: "2024-07-09",
    nextSession: "2024-07-16",
    totalSessions: 3,
    email: "emily@email.com",
    phone: "+1 555-0107",
    tags: ["Anxiety"],
  },
  {
    id: "p-8",
    name: "Raj Patel",
    initials: "RP",
    status: "Inactive",
    primaryConcern: "Career transition",
    lastSession: "2024-06-01",
    nextSession: null,
    totalSessions: 4,
    email: "raj@email.com",
    phone: "+1 555-0111",
    tags: ["Career"],
  },
  {
    id: "p-9",
    name: "Sarah Kim",
    initials: "SK",
    status: "Active",
    primaryConcern: "Sleep & stress",
    lastSession: null,
    nextSession: "2024-07-11",
    totalSessions: 1,
    email: "sarah@email.com",
    phone: "+1 555-0112",
    tags: ["Stress"],
  },
  {
    id: "p-10",
    name: "Olivia Bennett",
    initials: "OB",
    status: "Active",
    primaryConcern: "Postpartum anxiety",
    lastSession: "2024-07-02",
    nextSession: "2024-07-16",
    totalSessions: 5,
    email: "olivia@email.com",
    phone: "+1 555-0113",
    tags: ["Postpartum", "CBT"],
  },
  {
    id: "p-11",
    name: "Marcus Webb",
    initials: "MW",
    status: "Active",
    primaryConcern: "Anger management",
    lastSession: "2024-06-25",
    nextSession: "2024-07-15",
    totalSessions: 10,
    email: "marcus.webb@email.com",
    phone: "+1 555-0114",
    tags: ["Anger", "DBT"],
  },
  {
    id: "p-12",
    name: "Nina Torres",
    initials: "NT",
    status: "New",
    primaryConcern: "Relationship counseling",
    lastSession: null,
    nextSession: "2024-07-18",
    totalSessions: 0,
    email: "nina@email.com",
    phone: "+1 555-0115",
    tags: ["Relationships"],
  },
  {
    id: "p-13",
    name: "Ethan Brooks",
    initials: "EB",
    status: "Active",
    primaryConcern: "ADHD coaching",
    lastSession: "2024-06-30",
    nextSession: "2024-07-14",
    totalSessions: 7,
    email: "ethan@email.com",
    phone: "+1 555-0116",
    tags: ["ADHD"],
  },
  {
    id: "p-14",
    name: "Layla Hassan",
    initials: "LH",
    status: "Inactive",
    primaryConcern: "Depression",
    lastSession: "2024-05-14",
    nextSession: null,
    totalSessions: 11,
    email: "layla@email.com",
    phone: "+1 555-0117",
    tags: ["Depression"],
  },
  {
    id: "p-15",
    name: "Tom Whitfield",
    initials: "TW",
    status: "Active",
    primaryConcern: "Executive stress",
    lastSession: "2024-07-05",
    nextSession: "2024-07-19",
    totalSessions: 14,
    email: "tom@email.com",
    phone: "+1 555-0118",
    tags: ["Executive", "Stress"],
  },
  {
    id: "p-16",
    name: "Chloe Nguyen",
    initials: "CN",
    status: "Active",
    primaryConcern: "Eating disorder recovery",
    lastSession: "2024-07-04",
    nextSession: "2024-07-11",
    totalSessions: 18,
    email: "chloe@email.com",
    phone: "+1 555-0119",
    tags: ["Recovery", "CBT"],
  },
  {
    id: "p-17",
    name: "Victor Alvarez",
    initials: "VA",
    status: "New",
    primaryConcern: "Grief",
    lastSession: null,
    nextSession: "2024-07-17",
    totalSessions: 0,
    email: "victor@email.com",
    phone: "+1 555-0120",
    tags: ["Grief"],
  },
  {
    id: "p-18",
    name: "Grace Kim",
    initials: "GK",
    status: "Active",
    primaryConcern: "OCD",
    lastSession: "2024-06-27",
    nextSession: "2024-07-13",
    totalSessions: 20,
    email: "grace@email.com",
    phone: "+1 555-0121",
    tags: ["OCD", "ERP"],
  },
  {
    id: "p-19",
    name: "Ben Foster",
    initials: "BF",
    status: "Active",
    primaryConcern: "Substance recovery support",
    lastSession: "2024-07-06",
    nextSession: "2024-07-13",
    totalSessions: 22,
    email: "ben@email.com",
    phone: "+1 555-0122",
    tags: ["Recovery"],
  },
];

// The Patients page shows a representative sample of the 42 active patients
// tracked practice-wide (see PRACTICE_STATS.activePatients) — not exhaustive,
// to keep the mock dataset maintainable. The Dashboard's "Active patients"
// stat intentionally reads PRACTICE_STATS.activePatients (42), not
// PATIENTS.length, and the Patients page caption makes that gap explicit.

export const MEETINGS: Meeting[] = [
  // Today (TODAY = 2024-07-10)
  {
    id: "m-1",
    date: TODAY,
    time: "09:00",
    durationMin: 50,
    patientId: "p-1",
    patientName: "Alex Morgan",
    kind: "Individual therapy",
    mode: "Video",
    status: "upcoming",
    notes: "Follow-up on sleep hygiene homework from last session.",
  },
  {
    id: "m-2",
    date: TODAY,
    time: "10:30",
    durationMin: 60,
    patientId: "p-2",
    patientName: "Priya Shah",
    kind: "Assessment review",
    mode: "Video",
    status: "upcoming",
    notes: "Review burnout inventory results and set next steps.",
  },
  {
    id: "m-3",
    date: TODAY,
    time: "13:00",
    durationMin: 90,
    patientId: null,
    patientName: "Northwind exec cohort",
    kind: "Group coaching",
    mode: "In-person",
    status: "upcoming",
    notes: "Quarterly leadership resilience workshop, 6 attendees.",
  },
  {
    id: "m-4",
    date: TODAY,
    time: "15:00",
    durationMin: 45,
    patientId: "p-3",
    patientName: "Daniel Reyes",
    kind: "Executive coaching",
    mode: "Phone",
    status: "upcoming",
    notes: "Check in on delegation goals set last month.",
  },
  {
    id: "m-5",
    date: TODAY,
    time: "16:30",
    durationMin: 45,
    patientId: "p-4",
    patientName: "Meera Iyer",
    kind: "Intake",
    mode: "Video",
    status: "upcoming",
    notes: "First session — collect history and set treatment goals.",
  },
  // Past
  {
    id: "m-6",
    date: "2024-07-08",
    time: "11:00",
    durationMin: 50,
    patientId: "p-5",
    patientName: "Fatima Al-Hassan",
    kind: "Individual therapy",
    mode: "Video",
    status: "completed",
  },
  {
    id: "m-7",
    date: "2024-07-08",
    time: "14:00",
    durationMin: 60,
    patientId: "p-6",
    patientName: "James Okafor",
    kind: "Assessment review",
    mode: "In-person",
    status: "completed",
  },
  {
    id: "m-8",
    date: "2024-07-09",
    time: "09:30",
    durationMin: 50,
    patientId: "p-7",
    patientName: "Emily Clarke",
    kind: "Individual therapy",
    mode: "Video",
    status: "completed",
  },
  {
    id: "m-9",
    date: "2024-07-09",
    time: "16:00",
    durationMin: 45,
    patientId: "p-8",
    patientName: "Raj Patel",
    kind: "Executive coaching",
    mode: "Phone",
    status: "canceled",
  },
  // Upcoming (after today)
  {
    id: "m-10",
    date: "2024-07-11",
    time: "09:00",
    durationMin: 50,
    patientId: "p-9",
    patientName: "Sarah Kim",
    kind: "Individual therapy",
    mode: "Video",
    status: "upcoming",
  },
  {
    id: "m-11",
    date: "2024-07-11",
    time: "11:30",
    durationMin: 90,
    patientId: null,
    patientName: "Northwind exec cohort",
    kind: "Group coaching",
    mode: "In-person",
    status: "upcoming",
  },
  {
    id: "m-12",
    date: "2024-07-12",
    time: "10:00",
    durationMin: 50,
    patientId: "p-1",
    patientName: "Alex Morgan",
    kind: "Individual therapy",
    mode: "Video",
    status: "upcoming",
  },
  {
    id: "m-13",
    date: "2024-07-14",
    time: "13:30",
    durationMin: 60,
    patientId: "p-2",
    patientName: "Priya Shah",
    kind: "Assessment review",
    mode: "Video",
    status: "upcoming",
  },
];

export const DIARIES: DiaryEntry[] = [
  {
    id: "d-1",
    patientId: "p-1",
    patientName: "Alex Morgan",
    title: "Alex M. — SOAP note",
    status: "pending_review",
    submitted: "2 hours ago",
    excerpt: "Patient reports improved sleep quality since adopting the wind-down routine…",
    content:
      "Subjective: Patient reports improved sleep quality since adopting the wind-down routine discussed last session, though morning anxiety persists. Objective: Alert, oriented, mood congruent affect. Assessment: Generalized anxiety, trending stable with mild improvement. Plan: Continue weekly CBT sessions, introduce grounding exercises for morning anxiety, reassess in 2 weeks.",
  },
  {
    id: "d-2",
    patientId: "p-2",
    patientName: "Priya Shah",
    title: "Priya S. — Treatment plan v2",
    status: "pending_review",
    submitted: "5 hours ago",
    excerpt: "Updated plan shifts focus from acute burnout symptoms to sustainable pacing…",
    content:
      "Updated treatment plan shifts focus from acute burnout symptoms to sustainable workload pacing. Goals: (1) Reduce weekly overtime hours below 5, (2) Establish a consistent lunch break, (3) Weekly check-ins on energy levels using a 1-10 scale. Reassess burnout inventory in 6 weeks.",
  },
  {
    id: "d-3",
    patientId: "p-3",
    patientName: "Daniel Reyes",
    title: "Daniel R. — Progress review",
    status: "pending_review",
    submitted: "Yesterday",
    excerpt: "Delegation goals largely met; still avoiding difficult conversations with reports…",
    content:
      "Progress review: Delegation goals largely met this month — client has handed off two recurring projects to direct reports. Still avoiding difficult performance conversations with underperforming team members. Plan: Role-play a specific upcoming conversation next session, revisit in 3 weeks.",
  },
  {
    id: "d-4",
    patientId: "p-4",
    patientName: "Meera Iyer",
    title: "Meera I. — Intake summary",
    status: "reviewed",
    submitted: "2 days ago",
    excerpt: "First intake session completed; presenting with generalized anxiety symptoms…",
    content:
      "Intake summary: Client presents with generalized anxiety symptoms of roughly 8 months duration, no prior therapy history. No acute risk indicators. Recommended weekly CBT-based individual therapy, reassess after 6 sessions. Initial homework: daily mood/anxiety log.",
    clinicianNote: "Reviewed and filed — scheduled first full session for 2024-07-10.",
  },
  {
    id: "d-5",
    patientId: "p-6",
    patientName: "James Okafor",
    title: "James O. — Trauma session notes",
    status: "reviewed",
    submitted: "1 week ago",
    excerpt: "Continued EMDR processing of target memory; SUDS reduced from 7 to 4…",
    content:
      "EMDR session notes: Continued processing of target memory identified in prior session. SUDS rating reduced from 7 to 4 over the course of the session. Client tolerated bilateral stimulation well. Plan: Continue processing next session, monitor for abreaction between sessions.",
    clinicianNote: "Consistent with treatment plan — no changes needed.",
  },
  {
    id: "d-6",
    patientId: "p-8",
    patientName: "Raj Patel",
    title: "Raj P. — Discharge summary",
    status: "reviewed",
    submitted: "3 weeks ago",
    excerpt: "Client has met career-transition goals and elected to pause ongoing sessions…",
    content:
      "Discharge summary: Client has met the primary goals of career-transition coaching, including finalizing a job offer and negotiating start terms. Elected to pause ongoing sessions with the option to resume if needed. Provided resources for continued self-directed check-ins.",
    clinicianNote: "Filed. Follow-up reminder set for 3 months out.",
  },
];

export const NOTIFICATIONS: PortalNotification[] = [
  {
    id: "n-1",
    kind: "meeting",
    title: "New meeting request",
    body: "Sarah Kim requested a session for Jul 11, 09:00.",
    time: "10 min ago",
    read: false,
    actionTo: "/psychologist/meetings",
    actionSearch: { open: "m-10" },
  },
  {
    id: "n-2",
    kind: "diary",
    title: "New diary submitted",
    body: "Alex Morgan submitted a SOAP note for review.",
    time: "2 hr ago",
    read: false,
    actionTo: "/psychologist/diaries",
    actionSearch: { open: "d-1" },
  },
  {
    id: "n-3",
    kind: "message",
    title: "New message",
    body: "Priya Shah sent a message about rescheduling.",
    time: "3 hr ago",
    read: false,
    actionTo: "/psychologist/patients",
    actionSearch: { open: "p-2" },
  },
  {
    id: "n-4",
    kind: "system",
    title: "Verification renewed",
    body: "Your license verification was renewed for another year.",
    time: "Yesterday",
    read: true,
  },
  {
    id: "n-5",
    kind: "meeting",
    title: "Session reminder",
    body: "Executive coaching with Daniel Reyes starts in 30 minutes.",
    time: "Yesterday",
    read: true,
    actionTo: "/psychologist/meetings",
    actionSearch: { open: "m-4" },
  },
  {
    id: "n-6",
    kind: "diary",
    title: "Diary reviewed",
    body: "Meera Iyer's intake summary was marked reviewed.",
    time: "2 days ago",
    read: true,
    actionTo: "/psychologist/diaries",
    actionSearch: { open: "d-4" },
  },
  {
    id: "n-7",
    kind: "system",
    title: "Platform update",
    body: "A new analytics dashboard is now available for your practice.",
    time: "3 days ago",
    read: true,
    actionTo: "/psychologist/analytics",
  },
];

export const WEEKLY_SESSIONS: WeeklySessions[] = [
  { week: "May 20", sessions: 18 },
  { week: "May 27", sessions: 22 },
  { week: "Jun 3", sessions: 19 },
  { week: "Jun 10", sessions: 25 },
  { week: "Jun 17", sessions: 28 },
  { week: "Jun 24", sessions: 24 },
  { week: "Jul 1", sessions: 30 },
  { week: "Jul 8", sessions: 34 },
];

export const SESSION_TYPE_BREAKDOWN: SessionTypeSlice[] = [
  { type: "Individual therapy", value: 42 },
  { type: "Executive coaching", value: 20 },
  { type: "Assessment review", value: 15 },
  { type: "Group coaching", value: 13 },
  { type: "Intake", value: 10 },
];

export const PATIENT_GROWTH: PatientGrowthPoint[] = [
  { month: "Nov", patients: 26 },
  { month: "Dec", patients: 28 },
  { month: "Jan", patients: 30 },
  { month: "Feb", patients: 31 },
  { month: "Mar", patients: 33 },
  { month: "Apr", patients: 35 },
  { month: "May", patients: 37 },
  { month: "Jun", patients: 40 },
  { month: "Jul", patients: 42 },
];

export const PROFILE: PsychologistProfile = {
  name: "Dr. Aditi Carter",
  title: "Clinical Psychologist, PsyD",
  email: "aditi@psych.com",
  phone: "+1 555-0102",
  license: "PSY-2019-014",
  specialties: ["Cognitive Behavioral Therapy", "Executive Coaching", "Trauma-Informed Care"],
  bio: "Dr. Carter has spent over a decade helping individuals and leaders build resilience through evidence-based, research-backed therapy and coaching.",
  hours: [
    { day: "Monday", range: "9:00 AM – 5:00 PM" },
    { day: "Tuesday", range: "9:00 AM – 5:00 PM" },
    { day: "Wednesday", range: "9:00 AM – 6:00 PM" },
    { day: "Thursday", range: "9:00 AM – 5:00 PM" },
    { day: "Friday", range: "9:00 AM – 2:00 PM" },
  ],
  notificationPrefs: {
    emailDigests: true,
    sessionReminders: true,
    diaryAlerts: true,
    marketing: false,
  },
};

export const PRACTICE_STATS = {
  todaysMeetings: MEETINGS.filter((m) => m.date === TODAY).length,
  activePatients: 42,
  diariesPending: DIARIES.filter((d) => d.status === "pending_review").length,
  notificationsTotal: NOTIFICATIONS.length,
};
