/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecureAdminPortalRouteImport } from './routes/secure-admin-portal'
import { Route as PsychologistRouteImport } from './routes/psychologist'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientMessagesRouteImport } from './routes/patient.messages'
import { Route as PatientDoctorsRouteImport } from './routes/patient.doctors'
import { Route as PatientBookingsRouteImport } from './routes/patient.bookings'
import { Route as PatientAssessmentsRouteImport } from './routes/patient.assessments'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecureAdminPortalRoute = SecureAdminPortalRouteImport.update({
  id: '/secure-admin-portal',
  path: '/secure-admin-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologistRoute = PsychologistRouteImport.update({
  id: '/psychologist',
  path: '/psychologist',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMessagesRoute = PatientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDoctorsRoute = PatientDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBookingsRoute = PatientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAssessmentsRoute = PatientAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/psychologist': typeof PsychologistRoute
  '/secure-admin-portal': typeof SecureAdminPortalRoute
  '/services': typeof ServicesRoute
  '/patient/assessments': typeof PatientAssessmentsRoute
  '/patient/bookings': typeof PatientBookingsRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/psychologist': typeof PsychologistRoute
  '/secure-admin-portal': typeof SecureAdminPortalRoute
  '/services': typeof ServicesRoute
  '/patient/assessments': typeof PatientAssessmentsRoute
  '/patient/bookings': typeof PatientBookingsRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/psychologist': typeof PsychologistRoute
  '/secure-admin-portal': typeof SecureAdminPortalRoute
  '/services': typeof ServicesRoute
  '/patient/assessments': typeof PatientAssessmentsRoute
  '/patient/bookings': typeof PatientBookingsRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/patient'
    | '/psychologist'
    | '/secure-admin-portal'
    | '/services'
    | '/patient/assessments'
    | '/patient/bookings'
    | '/patient/doctors'
    | '/patient/messages'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/psychologist'
    | '/secure-admin-portal'
    | '/services'
    | '/patient/assessments'
    | '/patient/bookings'
    | '/patient/doctors'
    | '/patient/messages'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/patient'
    | '/psychologist'
    | '/secure-admin-portal'
    | '/services'
    | '/patient/assessments'
    | '/patient/bookings'
    | '/patient/doctors'
    | '/patient/messages'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  PsychologistRoute: typeof PsychologistRoute
  SecureAdminPortalRoute: typeof SecureAdminPortalRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secure-admin-portal': {
      id: '/secure-admin-portal'
      path: '/secure-admin-portal'
      fullPath: '/secure-admin-portal'
      preLoaderRoute: typeof SecureAdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychologist': {
      id: '/psychologist'
      path: '/psychologist'
      fullPath: '/psychologist'
      preLoaderRoute: typeof PsychologistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/messages': {
      id: '/patient/messages'
      path: '/messages'
      fullPath: '/patient/messages'
      preLoaderRoute: typeof PatientMessagesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/doctors': {
      id: '/patient/doctors'
      path: '/doctors'
      fullPath: '/patient/doctors'
      preLoaderRoute: typeof PatientDoctorsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/bookings': {
      id: '/patient/bookings'
      path: '/bookings'
      fullPath: '/patient/bookings'
      preLoaderRoute: typeof PatientBookingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/assessments': {
      id: '/patient/assessments'
      path: '/assessments'
      fullPath: '/patient/assessments'
      preLoaderRoute: typeof PatientAssessmentsRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface PatientRouteChildren {
  PatientAssessmentsRoute: typeof PatientAssessmentsRoute
  PatientBookingsRoute: typeof PatientBookingsRoute
  PatientDoctorsRoute: typeof PatientDoctorsRoute
  PatientMessagesRoute: typeof PatientMessagesRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAssessmentsRoute: PatientAssessmentsRoute,
  PatientBookingsRoute: PatientBookingsRoute,
  PatientDoctorsRoute: PatientDoctorsRoute,
  PatientMessagesRoute: PatientMessagesRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  PsychologistRoute: PsychologistRoute,
  SecureAdminPortalRoute: SecureAdminPortalRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
