/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecureAdminPortalRouteImport } from './routes/secure-admin-portal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalManagementAccessRouteImport } from './routes/portal-management-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PsychologistRouteRouteImport } from './routes/psychologist/route'
import { Route as EmployeeRouteRouteImport } from './routes/employee/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PsychologistIndexRouteImport } from './routes/psychologist/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as PsychologistSupportRouteImport } from './routes/psychologist/support'
import { Route as PsychologistProfileRouteImport } from './routes/psychologist/profile'
import { Route as PsychologistPatientsRouteImport } from './routes/psychologist/patients'
import { Route as PsychologistNotificationsRouteImport } from './routes/psychologist/notifications'
import { Route as PsychologistMeetingsRouteImport } from './routes/psychologist/meetings'
import { Route as PsychologistDiariesRouteImport } from './routes/psychologist/diaries'
import { Route as PsychologistAnalyticsRouteImport } from './routes/psychologist/analytics'
import { Route as EmployeeSupportRouteImport } from './routes/employee/support'
import { Route as EmployeeSessionsRouteImport } from './routes/employee/sessions'
import { Route as EmployeeProfileRouteImport } from './routes/employee/profile'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee/notifications'
import { Route as EmployeeJournalRouteImport } from './routes/employee/journal'
import { Route as EmployeeCareTeamRouteImport } from './routes/employee/care-team'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as EmployeeBookIndexRouteImport } from './routes/employee/book/index'
import { Route as PsychologistSettingsConnectCalendarRouteImport } from './routes/psychologist/settings/connect-calendar'
import { Route as EmployeeBookClinicianIdRouteImport } from './routes/employee/book/$clinicianId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google.callback'
import { Route as PsychologistSettingsConnectCalendarCallbackRouteImport } from './routes/psychologist/settings/connect-calendar.callback'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecureAdminPortalRoute = SecureAdminPortalRouteImport.update({
  id: '/secure-admin-portal',
  path: '/secure-admin-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalManagementAccessRoute = PortalManagementAccessRouteImport.update({
  id: '/portal-management-access',
  path: '/portal-management-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologistRouteRoute = PsychologistRouteRouteImport.update({
  id: '/psychologist',
  path: '/psychologist',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRouteRoute = EmployeeRouteRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologistIndexRoute = PsychologistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const PsychologistSupportRoute = PsychologistSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const PsychologistProfileRoute = PsychologistProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const PsychologistPatientsRoute = PsychologistPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const PsychologistNotificationsRoute =
  PsychologistNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PsychologistRouteRoute,
  } as any)
const PsychologistMeetingsRoute = PsychologistMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const PsychologistDiariesRoute = PsychologistDiariesRouteImport.update({
  id: '/diaries',
  path: '/diaries',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const PsychologistAnalyticsRoute = PsychologistAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const EmployeeSupportRoute = EmployeeSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeSessionsRoute = EmployeeSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeJournalRoute = EmployeeJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeCareTeamRoute = EmployeeCareTeamRouteImport.update({
  id: '/care-team',
  path: '/care-team',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeBookIndexRoute = EmployeeBookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const PsychologistSettingsConnectCalendarRoute =
  PsychologistSettingsConnectCalendarRouteImport.update({
    id: '/settings/connect-calendar',
    path: '/settings/connect-calendar',
    getParentRoute: () => PsychologistRouteRoute,
  } as any)
const EmployeeBookClinicianIdRoute = EmployeeBookClinicianIdRouteImport.update({
  id: '/book/$clinicianId',
  path: '/book/$clinicianId',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGoogleRoute,
} as any)
const PsychologistSettingsConnectCalendarCallbackRoute =
  PsychologistSettingsConnectCalendarCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => PsychologistSettingsConnectCalendarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/psychologist': typeof PsychologistRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal-management-access': typeof PortalManagementAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/secure-admin-portal': typeof SecureAdminPortalRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/employee/care-team': typeof EmployeeCareTeamRoute
  '/employee/journal': typeof EmployeeJournalRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/sessions': typeof EmployeeSessionsRoute
  '/employee/support': typeof EmployeeSupportRoute
  '/psychologist/analytics': typeof PsychologistAnalyticsRoute
  '/psychologist/diaries': typeof PsychologistDiariesRoute
  '/psychologist/meetings': typeof PsychologistMeetingsRoute
  '/psychologist/notifications': typeof PsychologistNotificationsRoute
  '/psychologist/patients': typeof PsychologistPatientsRoute
  '/psychologist/profile': typeof PsychologistProfileRoute
  '/psychologist/support': typeof PsychologistSupportRoute
  '/employee/': typeof EmployeeIndexRoute
  '/psychologist/': typeof PsychologistIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/employee/book/$clinicianId': typeof EmployeeBookClinicianIdRoute
  '/psychologist/settings/connect-calendar': typeof PsychologistSettingsConnectCalendarRouteWithChildren
  '/employee/book/': typeof EmployeeBookIndexRoute
  '/psychologist/settings/connect-calendar/callback': typeof PsychologistSettingsConnectCalendarCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal-management-access': typeof PortalManagementAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/secure-admin-portal': typeof SecureAdminPortalRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/employee/care-team': typeof EmployeeCareTeamRoute
  '/employee/journal': typeof EmployeeJournalRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/sessions': typeof EmployeeSessionsRoute
  '/employee/support': typeof EmployeeSupportRoute
  '/psychologist/analytics': typeof PsychologistAnalyticsRoute
  '/psychologist/diaries': typeof PsychologistDiariesRoute
  '/psychologist/meetings': typeof PsychologistMeetingsRoute
  '/psychologist/notifications': typeof PsychologistNotificationsRoute
  '/psychologist/patients': typeof PsychologistPatientsRoute
  '/psychologist/profile': typeof PsychologistProfileRoute
  '/psychologist/support': typeof PsychologistSupportRoute
  '/employee': typeof EmployeeIndexRoute
  '/psychologist': typeof PsychologistIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/employee/book/$clinicianId': typeof EmployeeBookClinicianIdRoute
  '/psychologist/settings/connect-calendar': typeof PsychologistSettingsConnectCalendarRouteWithChildren
  '/employee/book': typeof EmployeeBookIndexRoute
  '/psychologist/settings/connect-calendar/callback': typeof PsychologistSettingsConnectCalendarCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/psychologist': typeof PsychologistRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal-management-access': typeof PortalManagementAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/secure-admin-portal': typeof SecureAdminPortalRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/employee/care-team': typeof EmployeeCareTeamRoute
  '/employee/journal': typeof EmployeeJournalRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/sessions': typeof EmployeeSessionsRoute
  '/employee/support': typeof EmployeeSupportRoute
  '/psychologist/analytics': typeof PsychologistAnalyticsRoute
  '/psychologist/diaries': typeof PsychologistDiariesRoute
  '/psychologist/meetings': typeof PsychologistMeetingsRoute
  '/psychologist/notifications': typeof PsychologistNotificationsRoute
  '/psychologist/patients': typeof PsychologistPatientsRoute
  '/psychologist/profile': typeof PsychologistProfileRoute
  '/psychologist/support': typeof PsychologistSupportRoute
  '/employee/': typeof EmployeeIndexRoute
  '/psychologist/': typeof PsychologistIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/employee/book/$clinicianId': typeof EmployeeBookClinicianIdRoute
  '/psychologist/settings/connect-calendar': typeof PsychologistSettingsConnectCalendarRouteWithChildren
  '/employee/book/': typeof EmployeeBookIndexRoute
  '/psychologist/settings/connect-calendar/callback': typeof PsychologistSettingsConnectCalendarCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/psychologist'
    | '/about'
    | '/booking'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/portal-management-access'
    | '/reset-password'
    | '/secure-admin-portal'
    | '/services'
    | '/signup'
    | '/verify-email'
    | '/auth/google'
    | '/employee/care-team'
    | '/employee/journal'
    | '/employee/notifications'
    | '/employee/profile'
    | '/employee/sessions'
    | '/employee/support'
    | '/psychologist/analytics'
    | '/psychologist/diaries'
    | '/psychologist/meetings'
    | '/psychologist/notifications'
    | '/psychologist/patients'
    | '/psychologist/profile'
    | '/psychologist/support'
    | '/employee/'
    | '/psychologist/'
    | '/auth/google/callback'
    | '/employee/book/$clinicianId'
    | '/psychologist/settings/connect-calendar'
    | '/employee/book/'
    | '/psychologist/settings/connect-calendar/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/portal-management-access'
    | '/reset-password'
    | '/secure-admin-portal'
    | '/services'
    | '/signup'
    | '/verify-email'
    | '/auth/google'
    | '/employee/care-team'
    | '/employee/journal'
    | '/employee/notifications'
    | '/employee/profile'
    | '/employee/sessions'
    | '/employee/support'
    | '/psychologist/analytics'
    | '/psychologist/diaries'
    | '/psychologist/meetings'
    | '/psychologist/notifications'
    | '/psychologist/patients'
    | '/psychologist/profile'
    | '/psychologist/support'
    | '/employee'
    | '/psychologist'
    | '/auth/google/callback'
    | '/employee/book/$clinicianId'
    | '/psychologist/settings/connect-calendar'
    | '/employee/book'
    | '/psychologist/settings/connect-calendar/callback'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/psychologist'
    | '/about'
    | '/booking'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/portal-management-access'
    | '/reset-password'
    | '/secure-admin-portal'
    | '/services'
    | '/signup'
    | '/verify-email'
    | '/auth/google'
    | '/employee/care-team'
    | '/employee/journal'
    | '/employee/notifications'
    | '/employee/profile'
    | '/employee/sessions'
    | '/employee/support'
    | '/psychologist/analytics'
    | '/psychologist/diaries'
    | '/psychologist/meetings'
    | '/psychologist/notifications'
    | '/psychologist/patients'
    | '/psychologist/profile'
    | '/psychologist/support'
    | '/employee/'
    | '/psychologist/'
    | '/auth/google/callback'
    | '/employee/book/$clinicianId'
    | '/psychologist/settings/connect-calendar'
    | '/employee/book/'
    | '/psychologist/settings/connect-calendar/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRouteRoute: typeof EmployeeRouteRouteWithChildren
  PsychologistRouteRoute: typeof PsychologistRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalManagementAccessRoute: typeof PortalManagementAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecureAdminPortalRoute: typeof SecureAdminPortalRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthGoogleRoute: typeof AuthGoogleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secure-admin-portal': {
      id: '/secure-admin-portal'
      path: '/secure-admin-portal'
      fullPath: '/secure-admin-portal'
      preLoaderRoute: typeof SecureAdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-management-access': {
      id: '/portal-management-access'
      path: '/portal-management-access'
      fullPath: '/portal-management-access'
      preLoaderRoute: typeof PortalManagementAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychologist': {
      id: '/psychologist'
      path: '/psychologist'
      fullPath: '/psychologist'
      preLoaderRoute: typeof PsychologistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychologist/': {
      id: '/psychologist/'
      path: '/'
      fullPath: '/psychologist/'
      preLoaderRoute: typeof PsychologistIndexRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/psychologist/support': {
      id: '/psychologist/support'
      path: '/support'
      fullPath: '/psychologist/support'
      preLoaderRoute: typeof PsychologistSupportRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/profile': {
      id: '/psychologist/profile'
      path: '/profile'
      fullPath: '/psychologist/profile'
      preLoaderRoute: typeof PsychologistProfileRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/patients': {
      id: '/psychologist/patients'
      path: '/patients'
      fullPath: '/psychologist/patients'
      preLoaderRoute: typeof PsychologistPatientsRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/notifications': {
      id: '/psychologist/notifications'
      path: '/notifications'
      fullPath: '/psychologist/notifications'
      preLoaderRoute: typeof PsychologistNotificationsRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/meetings': {
      id: '/psychologist/meetings'
      path: '/meetings'
      fullPath: '/psychologist/meetings'
      preLoaderRoute: typeof PsychologistMeetingsRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/diaries': {
      id: '/psychologist/diaries'
      path: '/diaries'
      fullPath: '/psychologist/diaries'
      preLoaderRoute: typeof PsychologistDiariesRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/analytics': {
      id: '/psychologist/analytics'
      path: '/analytics'
      fullPath: '/psychologist/analytics'
      preLoaderRoute: typeof PsychologistAnalyticsRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/employee/support': {
      id: '/employee/support'
      path: '/support'
      fullPath: '/employee/support'
      preLoaderRoute: typeof EmployeeSupportRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/sessions': {
      id: '/employee/sessions'
      path: '/sessions'
      fullPath: '/employee/sessions'
      preLoaderRoute: typeof EmployeeSessionsRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/journal': {
      id: '/employee/journal'
      path: '/journal'
      fullPath: '/employee/journal'
      preLoaderRoute: typeof EmployeeJournalRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/care-team': {
      id: '/employee/care-team'
      path: '/care-team'
      fullPath: '/employee/care-team'
      preLoaderRoute: typeof EmployeeCareTeamRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/book/': {
      id: '/employee/book/'
      path: '/book'
      fullPath: '/employee/book/'
      preLoaderRoute: typeof EmployeeBookIndexRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/psychologist/settings/connect-calendar': {
      id: '/psychologist/settings/connect-calendar'
      path: '/settings/connect-calendar'
      fullPath: '/psychologist/settings/connect-calendar'
      preLoaderRoute: typeof PsychologistSettingsConnectCalendarRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/employee/book/$clinicianId': {
      id: '/employee/book/$clinicianId'
      path: '/book/$clinicianId'
      fullPath: '/employee/book/$clinicianId'
      preLoaderRoute: typeof EmployeeBookClinicianIdRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthGoogleRoute
    }
    '/psychologist/settings/connect-calendar/callback': {
      id: '/psychologist/settings/connect-calendar/callback'
      path: '/callback'
      fullPath: '/psychologist/settings/connect-calendar/callback'
      preLoaderRoute: typeof PsychologistSettingsConnectCalendarCallbackRouteImport
      parentRoute: typeof PsychologistSettingsConnectCalendarRoute
    }
  }
}

interface EmployeeRouteRouteChildren {
  EmployeeCareTeamRoute: typeof EmployeeCareTeamRoute
  EmployeeJournalRoute: typeof EmployeeJournalRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeSessionsRoute: typeof EmployeeSessionsRoute
  EmployeeSupportRoute: typeof EmployeeSupportRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  EmployeeBookClinicianIdRoute: typeof EmployeeBookClinicianIdRoute
  EmployeeBookIndexRoute: typeof EmployeeBookIndexRoute
}

const EmployeeRouteRouteChildren: EmployeeRouteRouteChildren = {
  EmployeeCareTeamRoute: EmployeeCareTeamRoute,
  EmployeeJournalRoute: EmployeeJournalRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeSessionsRoute: EmployeeSessionsRoute,
  EmployeeSupportRoute: EmployeeSupportRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  EmployeeBookClinicianIdRoute: EmployeeBookClinicianIdRoute,
  EmployeeBookIndexRoute: EmployeeBookIndexRoute,
}

const EmployeeRouteRouteWithChildren = EmployeeRouteRoute._addFileChildren(
  EmployeeRouteRouteChildren,
)

interface PsychologistSettingsConnectCalendarRouteChildren {
  PsychologistSettingsConnectCalendarCallbackRoute: typeof PsychologistSettingsConnectCalendarCallbackRoute
}

const PsychologistSettingsConnectCalendarRouteChildren: PsychologistSettingsConnectCalendarRouteChildren =
  {
    PsychologistSettingsConnectCalendarCallbackRoute:
      PsychologistSettingsConnectCalendarCallbackRoute,
  }

const PsychologistSettingsConnectCalendarRouteWithChildren =
  PsychologistSettingsConnectCalendarRoute._addFileChildren(
    PsychologistSettingsConnectCalendarRouteChildren,
  )

interface PsychologistRouteRouteChildren {
  PsychologistAnalyticsRoute: typeof PsychologistAnalyticsRoute
  PsychologistDiariesRoute: typeof PsychologistDiariesRoute
  PsychologistMeetingsRoute: typeof PsychologistMeetingsRoute
  PsychologistNotificationsRoute: typeof PsychologistNotificationsRoute
  PsychologistPatientsRoute: typeof PsychologistPatientsRoute
  PsychologistProfileRoute: typeof PsychologistProfileRoute
  PsychologistSupportRoute: typeof PsychologistSupportRoute
  PsychologistIndexRoute: typeof PsychologistIndexRoute
  PsychologistSettingsConnectCalendarRoute: typeof PsychologistSettingsConnectCalendarRouteWithChildren
}

const PsychologistRouteRouteChildren: PsychologistRouteRouteChildren = {
  PsychologistAnalyticsRoute: PsychologistAnalyticsRoute,
  PsychologistDiariesRoute: PsychologistDiariesRoute,
  PsychologistMeetingsRoute: PsychologistMeetingsRoute,
  PsychologistNotificationsRoute: PsychologistNotificationsRoute,
  PsychologistPatientsRoute: PsychologistPatientsRoute,
  PsychologistProfileRoute: PsychologistProfileRoute,
  PsychologistSupportRoute: PsychologistSupportRoute,
  PsychologistIndexRoute: PsychologistIndexRoute,
  PsychologistSettingsConnectCalendarRoute:
    PsychologistSettingsConnectCalendarRouteWithChildren,
}

const PsychologistRouteRouteWithChildren =
  PsychologistRouteRoute._addFileChildren(PsychologistRouteRouteChildren)

interface AuthGoogleRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthGoogleRouteChildren: AuthGoogleRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthGoogleRouteWithChildren = AuthGoogleRoute._addFileChildren(
  AuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRouteRoute: EmployeeRouteRouteWithChildren,
  PsychologistRouteRoute: PsychologistRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalManagementAccessRoute: PortalManagementAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecureAdminPortalRoute: SecureAdminPortalRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthGoogleRoute: AuthGoogleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
