/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecureAdminPortalRouteImport } from './routes/secure-admin-portal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalManagementAccessRouteImport } from './routes/portal-management-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PsychologistRouteRouteImport } from './routes/psychologist/route'
import { Route as ClientRouteRouteImport } from './routes/client/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PsychologistIndexRouteImport } from './routes/psychologist/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as PsychologistProfileRouteImport } from './routes/psychologist/profile'
import { Route as PsychologistPatientsRouteImport } from './routes/psychologist/patients'
import { Route as PsychologistNotificationsRouteImport } from './routes/psychologist/notifications'
import { Route as PsychologistMeetingsRouteImport } from './routes/psychologist/meetings'
import { Route as PsychologistDiariesRouteImport } from './routes/psychologist/diaries'
import { Route as PsychologistAnalyticsRouteImport } from './routes/psychologist/analytics'
import { Route as ClientSessionsRouteImport } from './routes/client/sessions'
import { Route as ClientProfileRouteImport } from './routes/client/profile'
import { Route as ClientNotificationsRouteImport } from './routes/client/notifications'
import { Route as ClientJournalRouteImport } from './routes/client/journal'
import { Route as ClientCareTeamRouteImport } from './routes/client/care-team'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google.callback'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecureAdminPortalRoute = SecureAdminPortalRouteImport.update({
  id: '/secure-admin-portal',
  path: '/secure-admin-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalManagementAccessRoute = PortalManagementAccessRouteImport.update({
  id: '/portal-management-access',
  path: '/portal-management-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologistRouteRoute = PsychologistRouteRouteImport.update({
  id: '/psychologist',
  path: '/psychologist',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologistIndexRoute = PsychologistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const PsychologistProfileRoute = PsychologistProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const PsychologistPatientsRoute = PsychologistPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const PsychologistNotificationsRoute =
  PsychologistNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PsychologistRouteRoute,
  } as any)
const PsychologistMeetingsRoute = PsychologistMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const PsychologistDiariesRoute = PsychologistDiariesRouteImport.update({
  id: '/diaries',
  path: '/diaries',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const PsychologistAnalyticsRoute = PsychologistAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PsychologistRouteRoute,
} as any)
const ClientSessionsRoute = ClientSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientJournalRoute = ClientJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientCareTeamRoute = ClientCareTeamRouteImport.update({
  id: '/care-team',
  path: '/care-team',
  getParentRoute: () => ClientRouteRoute,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteRouteWithChildren
  '/psychologist': typeof PsychologistRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal-management-access': typeof PortalManagementAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/secure-admin-portal': typeof SecureAdminPortalRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/client/care-team': typeof ClientCareTeamRoute
  '/client/journal': typeof ClientJournalRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/sessions': typeof ClientSessionsRoute
  '/psychologist/analytics': typeof PsychologistAnalyticsRoute
  '/psychologist/diaries': typeof PsychologistDiariesRoute
  '/psychologist/meetings': typeof PsychologistMeetingsRoute
  '/psychologist/notifications': typeof PsychologistNotificationsRoute
  '/psychologist/patients': typeof PsychologistPatientsRoute
  '/psychologist/profile': typeof PsychologistProfileRoute
  '/client/': typeof ClientIndexRoute
  '/psychologist/': typeof PsychologistIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal-management-access': typeof PortalManagementAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/secure-admin-portal': typeof SecureAdminPortalRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/client/care-team': typeof ClientCareTeamRoute
  '/client/journal': typeof ClientJournalRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/sessions': typeof ClientSessionsRoute
  '/psychologist/analytics': typeof PsychologistAnalyticsRoute
  '/psychologist/diaries': typeof PsychologistDiariesRoute
  '/psychologist/meetings': typeof PsychologistMeetingsRoute
  '/psychologist/notifications': typeof PsychologistNotificationsRoute
  '/psychologist/patients': typeof PsychologistPatientsRoute
  '/psychologist/profile': typeof PsychologistProfileRoute
  '/client': typeof ClientIndexRoute
  '/psychologist': typeof PsychologistIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteRouteWithChildren
  '/psychologist': typeof PsychologistRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal-management-access': typeof PortalManagementAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/secure-admin-portal': typeof SecureAdminPortalRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/client/care-team': typeof ClientCareTeamRoute
  '/client/journal': typeof ClientJournalRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/sessions': typeof ClientSessionsRoute
  '/psychologist/analytics': typeof PsychologistAnalyticsRoute
  '/psychologist/diaries': typeof PsychologistDiariesRoute
  '/psychologist/meetings': typeof PsychologistMeetingsRoute
  '/psychologist/notifications': typeof PsychologistNotificationsRoute
  '/psychologist/patients': typeof PsychologistPatientsRoute
  '/psychologist/profile': typeof PsychologistProfileRoute
  '/client/': typeof ClientIndexRoute
  '/psychologist/': typeof PsychologistIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/psychologist'
    | '/about'
    | '/booking'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/portal-management-access'
    | '/reset-password'
    | '/secure-admin-portal'
    | '/services'
    | '/signup'
    | '/verify-email'
    | '/auth/google'
    | '/client/care-team'
    | '/client/journal'
    | '/client/notifications'
    | '/client/profile'
    | '/client/sessions'
    | '/psychologist/analytics'
    | '/psychologist/diaries'
    | '/psychologist/meetings'
    | '/psychologist/notifications'
    | '/psychologist/patients'
    | '/psychologist/profile'
    | '/client/'
    | '/psychologist/'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/portal-management-access'
    | '/reset-password'
    | '/secure-admin-portal'
    | '/services'
    | '/signup'
    | '/verify-email'
    | '/auth/google'
    | '/client/care-team'
    | '/client/journal'
    | '/client/notifications'
    | '/client/profile'
    | '/client/sessions'
    | '/psychologist/analytics'
    | '/psychologist/diaries'
    | '/psychologist/meetings'
    | '/psychologist/notifications'
    | '/psychologist/patients'
    | '/psychologist/profile'
    | '/client'
    | '/psychologist'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/psychologist'
    | '/about'
    | '/booking'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/portal-management-access'
    | '/reset-password'
    | '/secure-admin-portal'
    | '/services'
    | '/signup'
    | '/verify-email'
    | '/auth/google'
    | '/client/care-team'
    | '/client/journal'
    | '/client/notifications'
    | '/client/profile'
    | '/client/sessions'
    | '/psychologist/analytics'
    | '/psychologist/diaries'
    | '/psychologist/meetings'
    | '/psychologist/notifications'
    | '/psychologist/patients'
    | '/psychologist/profile'
    | '/client/'
    | '/psychologist/'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  PsychologistRouteRoute: typeof PsychologistRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalManagementAccessRoute: typeof PortalManagementAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecureAdminPortalRoute: typeof SecureAdminPortalRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthGoogleRoute: typeof AuthGoogleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secure-admin-portal': {
      id: '/secure-admin-portal'
      path: '/secure-admin-portal'
      fullPath: '/secure-admin-portal'
      preLoaderRoute: typeof SecureAdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-management-access': {
      id: '/portal-management-access'
      path: '/portal-management-access'
      fullPath: '/portal-management-access'
      preLoaderRoute: typeof PortalManagementAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychologist': {
      id: '/psychologist'
      path: '/psychologist'
      fullPath: '/psychologist'
      preLoaderRoute: typeof PsychologistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychologist/': {
      id: '/psychologist/'
      path: '/'
      fullPath: '/psychologist/'
      preLoaderRoute: typeof PsychologistIndexRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/psychologist/profile': {
      id: '/psychologist/profile'
      path: '/profile'
      fullPath: '/psychologist/profile'
      preLoaderRoute: typeof PsychologistProfileRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/patients': {
      id: '/psychologist/patients'
      path: '/patients'
      fullPath: '/psychologist/patients'
      preLoaderRoute: typeof PsychologistPatientsRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/notifications': {
      id: '/psychologist/notifications'
      path: '/notifications'
      fullPath: '/psychologist/notifications'
      preLoaderRoute: typeof PsychologistNotificationsRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/meetings': {
      id: '/psychologist/meetings'
      path: '/meetings'
      fullPath: '/psychologist/meetings'
      preLoaderRoute: typeof PsychologistMeetingsRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/diaries': {
      id: '/psychologist/diaries'
      path: '/diaries'
      fullPath: '/psychologist/diaries'
      preLoaderRoute: typeof PsychologistDiariesRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/psychologist/analytics': {
      id: '/psychologist/analytics'
      path: '/analytics'
      fullPath: '/psychologist/analytics'
      preLoaderRoute: typeof PsychologistAnalyticsRouteImport
      parentRoute: typeof PsychologistRouteRoute
    }
    '/client/sessions': {
      id: '/client/sessions'
      path: '/sessions'
      fullPath: '/client/sessions'
      preLoaderRoute: typeof ClientSessionsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/journal': {
      id: '/client/journal'
      path: '/journal'
      fullPath: '/client/journal'
      preLoaderRoute: typeof ClientJournalRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/care-team': {
      id: '/client/care-team'
      path: '/care-team'
      fullPath: '/client/care-team'
      preLoaderRoute: typeof ClientCareTeamRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthGoogleRoute
    }
  }
}

interface ClientRouteRouteChildren {
  ClientCareTeamRoute: typeof ClientCareTeamRoute
  ClientJournalRoute: typeof ClientJournalRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientSessionsRoute: typeof ClientSessionsRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientCareTeamRoute: ClientCareTeamRoute,
  ClientJournalRoute: ClientJournalRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientSessionsRoute: ClientSessionsRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

interface PsychologistRouteRouteChildren {
  PsychologistAnalyticsRoute: typeof PsychologistAnalyticsRoute
  PsychologistDiariesRoute: typeof PsychologistDiariesRoute
  PsychologistMeetingsRoute: typeof PsychologistMeetingsRoute
  PsychologistNotificationsRoute: typeof PsychologistNotificationsRoute
  PsychologistPatientsRoute: typeof PsychologistPatientsRoute
  PsychologistProfileRoute: typeof PsychologistProfileRoute
  PsychologistIndexRoute: typeof PsychologistIndexRoute
}

const PsychologistRouteRouteChildren: PsychologistRouteRouteChildren = {
  PsychologistAnalyticsRoute: PsychologistAnalyticsRoute,
  PsychologistDiariesRoute: PsychologistDiariesRoute,
  PsychologistMeetingsRoute: PsychologistMeetingsRoute,
  PsychologistNotificationsRoute: PsychologistNotificationsRoute,
  PsychologistPatientsRoute: PsychologistPatientsRoute,
  PsychologistProfileRoute: PsychologistProfileRoute,
  PsychologistIndexRoute: PsychologistIndexRoute,
}

const PsychologistRouteRouteWithChildren =
  PsychologistRouteRoute._addFileChildren(PsychologistRouteRouteChildren)

interface AuthGoogleRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthGoogleRouteChildren: AuthGoogleRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthGoogleRouteWithChildren = AuthGoogleRoute._addFileChildren(
  AuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRouteRoute: ClientRouteRouteWithChildren,
  PsychologistRouteRoute: PsychologistRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalManagementAccessRoute: PortalManagementAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecureAdminPortalRoute: SecureAdminPortalRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthGoogleRoute: AuthGoogleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
